# ============ PYDANTIC SCHEMAS FOR REQUEST/RESPONSE VALIDATION ============
# Pydantic BaseModel classes define the contract for API data serialization.
# Each schema is used for:
#   1. REQUEST VALIDATION: Validates incoming JSON matches the model (automatic 422 error if invalid)
#   2. RESPONSE SERIALIZATION: Converts database objects to JSON responses
#   3. AUTO-DOCUMENTATION: FastAPI shows these schemas in Swagger UI at /docs
# 
# Types of Schemas:
#   - Create schemas: Accept data from client for resource creation (may exclude id, timestamps)
#   - Response schemas: Return data to client (include computed fields, timestamps)
#   - Login schemas: Special input schemas for authentication
#   - Token schemas: JWT token responses

from pydantic import BaseModel, EmailStr
from datetime import datetime
from typing import Optional
from typing import Literal

# ============ POST SCHEMAS ============

class Post(BaseModel):
    """Base Post schema with common fields"""
    title: str                          # Required: Post title must be a string
    content: str                        # Required: Post content/body must be a string
    published: bool = True              # Optional: Defaults to True if not provided in request

class PostCreate(Post):
    """Schema for POST /posts endpoint (create new post)
    
    Inherits all fields from Post - no additional validation needed.
    This separation allows for expansion (e.g., PostCreate might gain upload_file in future).
    """
    pass

class User(BaseModel):
    """Schema for user responses
    
    Used when returning user data to client.
    NOTE: Password is NOT included - never expose hashed passwords in responses.
    """
    id: int
    email: EmailStr                     # EmailStr validates email format automatically
    created_at: datetime

    class Config:
        from_attributes = True          # Allow ORM model conversion (SQLAlchemy → Pydantic)

class PostResponse(Post):
    """Schema for POST and GET response bodies
    
    Includes fields that are computed server-side (created_at, id, etc.).
    These fields should NOT be in request schemas but ARE included in responses.
    """
    id: int                             # Auto-generated by database
    created_at: datetime                # Auto-generated timestamp by database
    owner_id: int                      # Auto-generated by database
    owner: User                      # User who created this post
    class Config:
        from_attributes = True          # Allow ORM model conversion (SQLAlchemy → Pydantic)

class PostOut(BaseModel):
    Post: PostResponse
    votes: int

    class Config:
        from_attributes = True
# ============ USER SCHEMAS ============



class UserCreate(BaseModel):
    """Schema for POST /users endpoint (user registration)
    
    Accepts email and password from client. Password will be hashed before storage.
    """
    email: EmailStr                     # EmailStr: Pydantic validates email format (RFC 5321)
    password: str                       # Raw plaintext password - MUST be hashed before database storage

class UserLogin(BaseModel):
    """Schema for POST /login endpoint (authentication)
    
    Client sends email and password. Server verifies against stored hashed password.
    Similar to UserCreate but semantically different (create vs authenticate).
    """
    email: EmailStr
    password: str

# ============ AUTHENTICATION SCHEMAS ============

class Token(BaseModel):
    """Schema for JWT token responses
    
    Returned after successful login. Client stores this token and sends in future requests.
    Token format: "Bearer <JWT_STRING>" in Authorization header
    """
    access_token: str                   # The JWT token string
    token_type: str                     # Usually "bearer" - indicates authentication scheme

class TokenData(BaseModel):
    """Schema for decoded JWT payload
    
    After verifying token signature, JWT contains this data.
    Used internally to extract user info from token.
    
    Fields:
        id (str): User ID extracted from JWT payload
                  Optional allows validation to pass even for invalid tokens
                  (error is caught in verify_token() function instead)
    """
    id: Optional[str]                   # User ID stored in JWT. Optional allows for invalid tokens.
    

class Vote(BaseModel):
    """Schema for POST /vote endpoint (vote/like on a post)
    
    Client sends this to like or unlike a post.
    
    Fields:
        post_id (int): Which post to vote on
        dir (Literal[0, 1]): Vote direction
                             - 1 = Add vote/like
                             - 0 = Remove vote/unlike
    
    Examples:
        # Like a post:
        {"post_id": 5, "dir": 1}
        
        # Unlike a post:
        {"post_id": 5, "dir": 0}
    """
    post_id: int                        # Post ID to vote on (must exist)
    dir: Literal[0, 1]                  # Direction: 1=like, 0=unlike
    
